---
- name: Setup Self Hosted Proxy Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    domain: evoq.app
    press_url: https://evoq.app
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: proxy
    - role: docker
